{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-core-datastore",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-datastore-1.3.0.aar",
          "url": "foundation-core-datastore-1.3.0.aar",
          "size": 34156,
          "sha512": "7e6fbfaddce3dd5764a19ab281074d5b80ca5a1d6c93f0a8d271b73c4482c8ac81a1347446630a2bc9d7f7957b16eccf13c6ea87046c835ebad5f23dae7840ea",
          "sha256": "d213c2094d62a21bf56b75eef961037359dbaae23ede04d629509f56b8f6cbe0",
          "sha1": "1f899414012945a017af5186d5a4aafec42197a9",
          "md5": "16244b61c9f2a41a6fb06ad248bbbf7f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-datastore-1.3.0.aar",
          "url": "foundation-core-datastore-1.3.0.aar",
          "size": 34156,
          "sha512": "7e6fbfaddce3dd5764a19ab281074d5b80ca5a1d6c93f0a8d271b73c4482c8ac81a1347446630a2bc9d7f7957b16eccf13c6ea87046c835ebad5f23dae7840ea",
          "sha256": "d213c2094d62a21bf56b75eef961037359dbaae23ede04d629509f56b8f6cbe0",
          "sha1": "1f899414012945a017af5186d5a4aafec42197a9",
          "md5": "16244b61c9f2a41a6fb06ad248bbbf7f"
        }
      ]
    }
  ]
}
