{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-design-system",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-design-system-1.1.0.aar",
          "url": "foundation-design-system-1.1.0.aar",
          "size": 1420924,
          "sha512": "b1fce7fa658126f738f7408c40b317fa3d0543f4332cf99a1c57266f6dbfd51d9dbca34bc4bc710c8e953d370b93078967190a51533e0969f36ad89a829cfe0b",
          "sha256": "bea12bd1ad9c43b83b32f915d907579baf288222c41dab9725545adfbe74efee",
          "sha1": "ce9856d5a247b30e6176803597179741617cd539",
          "md5": "e1607f47170acfbc79b4d058d0e7b919"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.03.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-di",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-design-system-1.1.0.aar",
          "url": "foundation-design-system-1.1.0.aar",
          "size": 1420924,
          "sha512": "b1fce7fa658126f738f7408c40b317fa3d0543f4332cf99a1c57266f6dbfd51d9dbca34bc4bc710c8e953d370b93078967190a51533e0969f36ad89a829cfe0b",
          "sha256": "bea12bd1ad9c43b83b32f915d907579baf288222c41dab9725545adfbe74efee",
          "sha1": "ce9856d5a247b30e6176803597179741617cd539",
          "md5": "e1607f47170acfbc79b4d058d0e7b919"
        }
      ]
    }
  ]
}
