{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-data-permissions",
    "version": "1.3.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-permissions-1.3.0-beta.1.aar",
          "url": "foundation-data-permissions-1.3.0-beta.1.aar",
          "size": 30914,
          "sha512": "24702913c7f9a206f878e68780b8cd1292a9ea8b271c9f263d6a2843891d9751d27b476094cef4ff0e8bb4af5a385f3e22182406fe854f4d50b3f7c1d452602c",
          "sha256": "6fb41a8d5ae46b9e4fb6574c934a65cb9e758ad20af719c777fd3c45be8c2534",
          "sha1": "97d0faa7358a0efc4b4f2eed0898c30184d16689",
          "md5": "8d9cd08be83eb611f9f6ed0f6a53049f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.3.0-beta.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-datastore",
          "version": {
            "requires": "1.3.0-beta.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-permissions-1.3.0-beta.1.aar",
          "url": "foundation-data-permissions-1.3.0-beta.1.aar",
          "size": 30914,
          "sha512": "24702913c7f9a206f878e68780b8cd1292a9ea8b271c9f263d6a2843891d9751d27b476094cef4ff0e8bb4af5a385f3e22182406fe854f4d50b3f7c1d452602c",
          "sha256": "6fb41a8d5ae46b9e4fb6574c934a65cb9e758ad20af719c777fd3c45be8c2534",
          "sha1": "97d0faa7358a0efc4b4f2eed0898c30184d16689",
          "md5": "8d9cd08be83eb611f9f6ed0f6a53049f"
        }
      ]
    }
  ]
}
