{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-feature-permissions",
    "version": "1.1.0-beta.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-feature-permissions-1.1.0-beta.3.aar",
          "url": "foundation-feature-permissions-1.1.0-beta.3.aar",
          "size": 99333,
          "sha512": "9d06d903ed2c5ce5c57e16519ab27bbf7a22c269f4e99bbf8dea264e83c072de2520bc9367e2ebe3f7eb44e18fb53b9a54e8378b063bfca7af2bfbb05646bfc6",
          "sha256": "4b6fe2ad35b318cdefb101f97abca1264efca0f82e13fca354b120e1a0a2f912",
          "sha1": "fbd76c00bd4a372689dd5533afec8e2ef803743d",
          "md5": "7154844547d9ad110553cfa118ef0ed1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.03.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-di",
          "version": {
            "requires": "1.1.0-beta.3"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.1.0-beta.3"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-configuration",
          "version": {
            "requires": "1.1.0-beta.3"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-permissions",
          "version": {
            "requires": "1.1.0-beta.3"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-utils",
          "version": {
            "requires": "1.1.0-beta.3"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-design-system",
          "version": {
            "requires": "1.1.0-beta.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-feature-permissions-1.1.0-beta.3.aar",
          "url": "foundation-feature-permissions-1.1.0-beta.3.aar",
          "size": 99333,
          "sha512": "9d06d903ed2c5ce5c57e16519ab27bbf7a22c269f4e99bbf8dea264e83c072de2520bc9367e2ebe3f7eb44e18fb53b9a54e8378b063bfca7af2bfbb05646bfc6",
          "sha256": "4b6fe2ad35b318cdefb101f97abca1264efca0f82e13fca354b120e1a0a2f912",
          "sha1": "fbd76c00bd4a372689dd5533afec8e2ef803743d",
          "md5": "7154844547d9ad110553cfa118ef0ed1"
        }
      ]
    }
  ]
}
