{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-core-di",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-di-1.0.0.aar",
          "url": "foundation-core-di-1.0.0.aar",
          "size": 3793,
          "sha512": "263804ebdde5d0710abf00909569fa6aa58df4e3da2fbbe1f86b44e6d7817d886738cbfcb6786b28252bd5b8605f43cfa46e4e6ab005aa9558990093c3fc77d9",
          "sha256": "a150cbe8dd7dbac5b54da6908d819434f0cc78e72bc0bca03a4974fbaae2a579",
          "sha1": "25d82bf37acb8481ef5522ebdece7cbdd6633a16",
          "md5": "300ac22d245331d3e3a1b3d3c933692a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-di-1.0.0.aar",
          "url": "foundation-core-di-1.0.0.aar",
          "size": 3793,
          "sha512": "263804ebdde5d0710abf00909569fa6aa58df4e3da2fbbe1f86b44e6d7817d886738cbfcb6786b28252bd5b8605f43cfa46e4e6ab005aa9558990093c3fc77d9",
          "sha256": "a150cbe8dd7dbac5b54da6908d819434f0cc78e72bc0bca03a4974fbaae2a579",
          "sha1": "25d82bf37acb8481ef5522ebdece7cbdd6633a16",
          "md5": "300ac22d245331d3e3a1b3d3c933692a"
        }
      ]
    }
  ]
}
