{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-core-config",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-config-1.2.0.aar",
          "url": "foundation-core-config-1.2.0.aar",
          "size": 46237,
          "sha512": "4d0a05728b7de09fbe212ddd19c9d0653262dcdfe7c81e739fbe2e752a5c483c99c890555314e3da66f5a9c45d462359eb5e6b92c51b50fd9faf15b11dd69c96",
          "sha256": "e306db668d7d47ce459007ba51fd32656406b9e14dc1f86c9194a3b76c84cef0",
          "sha1": "c23a66f62ae55537b3ee6d97428ef5a22589205e",
          "md5": "d98fdc8d2deaae63eb954a97398df82b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-config-1.2.0.aar",
          "url": "foundation-core-config-1.2.0.aar",
          "size": 46237,
          "sha512": "4d0a05728b7de09fbe212ddd19c9d0653262dcdfe7c81e739fbe2e752a5c483c99c890555314e3da66f5a9c45d462359eb5e6b92c51b50fd9faf15b11dd69c96",
          "sha256": "e306db668d7d47ce459007ba51fd32656406b9e14dc1f86c9194a3b76c84cef0",
          "sha1": "c23a66f62ae55537b3ee6d97428ef5a22589205e",
          "md5": "d98fdc8d2deaae63eb954a97398df82b"
        }
      ]
    }
  ]
}
