{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-feature-permissions",
    "version": "1.2.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-feature-permissions-1.2.0-beta.1.aar",
          "url": "foundation-feature-permissions-1.2.0-beta.1.aar",
          "size": 112984,
          "sha512": "cd281d3129c3c7dd9b9bac65961a46540cb9fad391a0737b9eac4559e207afcb40a3df64895679139785fd9dad12adb349d9b36b18239d76eb4d2340d9ee7675",
          "sha256": "654af843651fdfeb5b5e82573b2d94180f60c8152fc29213980bd58c65a14f91",
          "sha1": "5750ffff963142c8dc9b95721a0a281457ad328a",
          "md5": "78e930dc83d21af5e85992a9fba1b63c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.03.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-di",
          "version": {
            "requires": "1.2.0-beta.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.2.0-beta.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-configuration",
          "version": {
            "requires": "1.2.0-beta.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-permissions",
          "version": {
            "requires": "1.2.0-beta.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-utils",
          "version": {
            "requires": "1.2.0-beta.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-design-system",
          "version": {
            "requires": "1.2.0-beta.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-feature-permissions-1.2.0-beta.1.aar",
          "url": "foundation-feature-permissions-1.2.0-beta.1.aar",
          "size": 112984,
          "sha512": "cd281d3129c3c7dd9b9bac65961a46540cb9fad391a0737b9eac4559e207afcb40a3df64895679139785fd9dad12adb349d9b36b18239d76eb4d2340d9ee7675",
          "sha256": "654af843651fdfeb5b5e82573b2d94180f60c8152fc29213980bd58c65a14f91",
          "sha1": "5750ffff963142c8dc9b95721a0a281457ad328a",
          "md5": "78e930dc83d21af5e85992a9fba1b63c"
        }
      ]
    }
  ]
}
