{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-core-datastore",
    "version": "1.2.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-datastore-1.2.0-beta.1.aar",
          "url": "foundation-core-datastore-1.2.0-beta.1.aar",
          "size": 34331,
          "sha512": "488e8ff7a88694870b39a89c619d86d746458d3bef2630985f5c4e4174f03ca1c1d1991ac08d8cfe9caeb0401c2987a9334aeab47f9befba6963ba671156d206",
          "sha256": "426e2042f096680c36ace8fe1fe30face6933cc2e63d237fb89593068820ec8c",
          "sha1": "1e350fab45546eec93534186546cdab260ac3d22",
          "md5": "a0c48a3601dd02fc8a9810fd01886889"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.2.0-beta.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-datastore-1.2.0-beta.1.aar",
          "url": "foundation-core-datastore-1.2.0-beta.1.aar",
          "size": 34331,
          "sha512": "488e8ff7a88694870b39a89c619d86d746458d3bef2630985f5c4e4174f03ca1c1d1991ac08d8cfe9caeb0401c2987a9334aeab47f9befba6963ba671156d206",
          "sha256": "426e2042f096680c36ace8fe1fe30face6933cc2e63d237fb89593068820ec8c",
          "sha1": "1e350fab45546eec93534186546cdab260ac3d22",
          "md5": "a0c48a3601dd02fc8a9810fd01886889"
        }
      ]
    }
  ]
}
