{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-data-configuration",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-configuration-1.0.1.aar",
          "url": "foundation-data-configuration-1.0.1.aar",
          "size": 875931,
          "sha512": "a912e588d45dde4e51929a29a0d8987fd55c064dc26d2fd72a73bc57e95b26a120df56883975d61c0fd1fd8de0138d6e7ec7c1b627d577b3d26d2f746f2513a8",
          "sha256": "0c39c8b5c41f08c0a2296cb678996466c822b0641c2e9336f19dbeb8a31142d3",
          "sha1": "15c4336cd5cfc6cf2e1ef80e6428e7d8c0ad956d",
          "md5": "a37ec8ba6bae11a5df4671872d053929"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-network",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-utils",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-datastore",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-configuration-1.0.1.aar",
          "url": "foundation-data-configuration-1.0.1.aar",
          "size": 875931,
          "sha512": "a912e588d45dde4e51929a29a0d8987fd55c064dc26d2fd72a73bc57e95b26a120df56883975d61c0fd1fd8de0138d6e7ec7c1b627d577b3d26d2f746f2513a8",
          "sha256": "0c39c8b5c41f08c0a2296cb678996466c822b0641c2e9336f19dbeb8a31142d3",
          "sha1": "15c4336cd5cfc6cf2e1ef80e6428e7d8c0ad956d",
          "md5": "a37ec8ba6bae11a5df4671872d053929"
        }
      ]
    }
  ]
}
