{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-data-analytics",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-analytics-1.2.0.aar",
          "url": "foundation-data-analytics-1.2.0.aar",
          "size": 137078,
          "sha512": "0962c1fe7c93b468d563c4d1875ea057d7c12d5b40cd2879815ffaa0b6fc77c395e5bd10311d1dbe9ee191fedddf5e52ad833480250b7901acc5b9b4583edda5",
          "sha256": "9fc3d7fc47ed5b606171b25a8bd505c8823b24bb969d13a7fcd7f4ebdc9c18df",
          "sha1": "c10357c065020f2d57f268cd1e38e94bd578b46e",
          "md5": "a108aba5ff6037eb0fe1630a41d0f7f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-network",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-configuration",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-datastore",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-analytics-1.2.0.aar",
          "url": "foundation-data-analytics-1.2.0.aar",
          "size": 137078,
          "sha512": "0962c1fe7c93b468d563c4d1875ea057d7c12d5b40cd2879815ffaa0b6fc77c395e5bd10311d1dbe9ee191fedddf5e52ad833480250b7901acc5b9b4583edda5",
          "sha256": "9fc3d7fc47ed5b606171b25a8bd505c8823b24bb969d13a7fcd7f4ebdc9c18df",
          "sha1": "c10357c065020f2d57f268cd1e38e94bd578b46e",
          "md5": "a108aba5ff6037eb0fe1630a41d0f7f5"
        }
      ]
    }
  ]
}
