{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-core-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-utils-1.0.0.aar",
          "url": "foundation-core-utils-1.0.0.aar",
          "size": 8445,
          "sha512": "201ddba93416a0b1628bebe7235bb13dbd07cccded6d8732a5f1ef8d849db02ea6ae0eaab5e2230ebd7ba411408830893285e8050d5efb49fe7b3d040679b088",
          "sha256": "1e38e865051b4f0bae32cf67fa4ae0f4de6c814e0daa8fd1a0b7e2db1fb5913f",
          "sha1": "e8af0e565f68cfded6ee44e414de3d1f34913420",
          "md5": "59feb7a73bf0b506ced1782b35c9ac9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-core-utils-1.0.0.aar",
          "url": "foundation-core-utils-1.0.0.aar",
          "size": 8445,
          "sha512": "201ddba93416a0b1628bebe7235bb13dbd07cccded6d8732a5f1ef8d849db02ea6ae0eaab5e2230ebd7ba411408830893285e8050d5efb49fe7b3d040679b088",
          "sha256": "1e38e865051b4f0bae32cf67fa4ae0f4de6c814e0daa8fd1a0b7e2db1fb5913f",
          "sha1": "e8af0e565f68cfded6ee44e414de3d1f34913420",
          "md5": "59feb7a73bf0b506ced1782b35c9ac9c"
        }
      ]
    }
  ]
}
