{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-data-permissions",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-permissions-1.0.1.aar",
          "url": "foundation-data-permissions-1.0.1.aar",
          "size": 22918,
          "sha512": "552cf3b6dc727e2e39d32d6a04986a0d65d575fbed285e50082940270eab45778ddfd65c18e91f1c2460696de5136d13339a4a7954c397aa3aba68e925373354",
          "sha256": "c3a26f7b88b0cc8138288e9a114bdd2b64b73a5081c2bd2d4eb3a84556eff4ed",
          "sha1": "d13b3e2b1754332d2e4ac5de0b137587a9909b10",
          "md5": "9501c8efb24d2cdeafa9ad5c08faedf7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-datastore",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-permissions-1.0.1.aar",
          "url": "foundation-data-permissions-1.0.1.aar",
          "size": 22918,
          "sha512": "552cf3b6dc727e2e39d32d6a04986a0d65d575fbed285e50082940270eab45778ddfd65c18e91f1c2460696de5136d13339a4a7954c397aa3aba68e925373354",
          "sha256": "c3a26f7b88b0cc8138288e9a114bdd2b64b73a5081c2bd2d4eb3a84556eff4ed",
          "sha1": "d13b3e2b1754332d2e4ac5de0b137587a9909b10",
          "md5": "9501c8efb24d2cdeafa9ad5c08faedf7"
        }
      ]
    }
  ]
}
