{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "sdk",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.2.0.aar",
          "url": "sdk-1.2.0.aar",
          "size": 115568,
          "sha512": "9f82b3c17f9b19a9bc79a19125f95740e14f2e8beba4f4937d06bec41da6dd70ce938f52bc3d1211b48ebcb561ab27c01111d7eb32222690fced9312403c01a6",
          "sha256": "57912eb6ae5b2ee8760b3c11c1858af6df836015a91a4268905c7bc55bd2d3c3",
          "sha1": "91fd7c8e503e8fa2a82c687a020da5b6971ba4f9",
          "md5": "4e9e9dee3db04095511cb5360d6e4be1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-di",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-datastore",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-network",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-utils",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-configuration",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-analytics",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-permissions",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-feature-host",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-feature-permissions",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-feature-consents",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.2.0.aar",
          "url": "sdk-1.2.0.aar",
          "size": 115568,
          "sha512": "9f82b3c17f9b19a9bc79a19125f95740e14f2e8beba4f4937d06bec41da6dd70ce938f52bc3d1211b48ebcb561ab27c01111d7eb32222690fced9312403c01a6",
          "sha256": "57912eb6ae5b2ee8760b3c11c1858af6df836015a91a4268905c7bc55bd2d3c3",
          "sha1": "91fd7c8e503e8fa2a82c687a020da5b6971ba4f9",
          "md5": "4e9e9dee3db04095511cb5360d6e4be1"
        }
      ]
    }
  ]
}
