{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-feature-consents",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-feature-consents-1.2.0.aar",
          "url": "foundation-feature-consents-1.2.0.aar",
          "size": 529572,
          "sha512": "c5b9d7c239b176ddba6ba38b6ea3b4c7e180a397d1520374b457a28d247479a424ff841a903b70392468cab96e83aff6a92e57817dff3da0e0d30a13f15198af",
          "sha256": "3bfaf0dbff0ce55050f07f256011b1ab49807ba31e137af63972aa5abcb6b034",
          "sha1": "e3effc4a47e2b7e5733bfdb960745cea473120e0",
          "md5": "ece7766f9171a75f6f353b912db5d088"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.03.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-di",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-configuration",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-data-analytics",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-design-system",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-feature-consents-1.2.0.aar",
          "url": "foundation-feature-consents-1.2.0.aar",
          "size": 529572,
          "sha512": "c5b9d7c239b176ddba6ba38b6ea3b4c7e180a397d1520374b457a28d247479a424ff841a903b70392468cab96e83aff6a92e57817dff3da0e0d30a13f15198af",
          "sha256": "3bfaf0dbff0ce55050f07f256011b1ab49807ba31e137af63972aa5abcb6b034",
          "sha1": "e3effc4a47e2b7e5733bfdb960745cea473120e0",
          "md5": "ece7766f9171a75f6f353b912db5d088"
        }
      ]
    }
  ]
}
