{
  "formatVersion": "1.1",
  "component": {
    "group": "io.axeptio",
    "module": "foundation-data-permissions",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-permissions-1.0.0.aar",
          "url": "foundation-data-permissions-1.0.0.aar",
          "size": 32535,
          "sha512": "19eb31ee3192740f75bbb1480c7b3514577fbe46aae1bcc19cc1a67d1833082380c2398d9643dfa09578f2d689488772c993afd9612ad30402f8d546f7a86c7d",
          "sha256": "bb35b43b64cebf16a9ca1bded4cd37d6c34aaaa6b2b541c02b2eab53b35f7fe9",
          "sha1": "18fd5751b0b7d26fc563e53e00b1641b9a5d63f4",
          "md5": "236fec00313135ccc59616cbb8f86e55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-config",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.axeptio",
          "module": "foundation-core-datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-data-permissions-1.0.0.aar",
          "url": "foundation-data-permissions-1.0.0.aar",
          "size": 32535,
          "sha512": "19eb31ee3192740f75bbb1480c7b3514577fbe46aae1bcc19cc1a67d1833082380c2398d9643dfa09578f2d689488772c993afd9612ad30402f8d546f7a86c7d",
          "sha256": "bb35b43b64cebf16a9ca1bded4cd37d6c34aaaa6b2b541c02b2eab53b35f7fe9",
          "sha1": "18fd5751b0b7d26fc563e53e00b1641b9a5d63f4",
          "md5": "236fec00313135ccc59616cbb8f86e55"
        }
      ]
    }
  ]
}
